name: Check Branch Name Format
on: [push]

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch name matches the format
        uses: goshencollege/validate-branch-name@v1.0.1
        with:
          pattern: "^feature\/[a-z0-9]+(-[a-z0-9]+)*$"
