name: Check Branch Name Format
on: [pull_request]

jobs:
  check_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch name matches the format
        run: |
          branch_name=$GITHUB_HEAD_REF
          format_regex="^feature\/[a-z0-9]+(\-[a-z0-9]+)*$"

          if [[ !("$branch_name" =~ $format_regex) ]]; then
            echo "Branch name $branch_name does not match the format."
            exit 1
          fi
        shell: bash
