name: Check PR
on:
  push:
    branches: feature/*
  pull_request:
    branches: feature/*

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint, test and build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build
